project_id = "zsqfzluyylzmmjtfxwgr"

[functions.twilio-inbound]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.process-knowledge-upload]
verify_jwt = false

[functions.calendar-oauth-callback]
verify_jwt = false

[functions.elevenlabs-init]
verify_jwt = false

[functions.elevenlabs-webhook]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.print-receipt]
verify_jwt = false

[functions.elevenlabs-check-service-area]
verify_jwt = false

[functions.create-dispatch-request]
verify_jwt = false

[functions.check-impound]
verify_jwt = false

[functions.get-impound-release-info]
verify_jwt = false

[functions.get-impound-lot-info]
verify_jwt = false

[functions.elevenlabs-lookup-dispatch-status]
verify_jwt = false

[functions.delete-tenant]
verify_jwt = false